name: pose-fitness-helper
services:
  mongo:
    image: mongo:latest
    ports:
    - 27017:27017

  backend:
    image: retryyy/pose-fitness-helper-be
    links:
      - "mongo:mongo"
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    image: retryyy/pose-fitness-helper-fe
    ports:
      - "4200:80"
